/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const EditableActivity = IDL.Record({
  'title' : IDL.Text,
  'description' : IDL.Text,
  'photos' : IDL.Vec(IDL.Text),
});
export const EditableAnnouncement = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
});
export const EditableEvent = IDL.Record({
  'title' : IDL.Text,
  'description' : IDL.Text,
  'location' : IDL.Text,
  'timestampNanos' : IDL.Nat64,
});
export const EditableGalleryImage = IDL.Record({
  'title' : IDL.Text,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
});
export const Activity = IDL.Record({
  'id' : IDL.Nat64,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'timestampNanos' : IDL.Int,
  'photos' : IDL.Vec(IDL.Text),
});
export const AlumniProfile = IDL.Record({
  'bio' : IDL.Text,
  'contactInfo' : IDL.Opt(IDL.Text),
  'currentCountry' : IDL.Text,
  'fullName' : IDL.Text,
  'graduationYear' : IDL.Nat16,
  'currentCity' : IDL.Text,
  'department' : IDL.Text,
});
export const Announcement = IDL.Record({
  'id' : IDL.Nat64,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'timestampNanos' : IDL.Int,
});
export const Event = IDL.Record({
  'id' : IDL.Nat64,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'location' : IDL.Text,
  'timestampNanos' : IDL.Nat64,
});
export const GalleryImage = IDL.Record({
  'id' : IDL.Nat64,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'timestampNanos' : IDL.Int,
});
export const ApprovalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const UserApprovalInfo = IDL.Record({
  'status' : ApprovalStatus,
  'principal' : IDL.Principal,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createActivity' : IDL.Func([EditableActivity], [], []),
  'createAnnouncement' : IDL.Func([EditableAnnouncement], [], []),
  'createEvent' : IDL.Func([EditableEvent], [], []),
  'createGalleryImage' : IDL.Func([EditableGalleryImage], [], []),
  'deleteActivity' : IDL.Func([IDL.Nat64], [], []),
  'deleteAnnouncement' : IDL.Func([IDL.Nat64], [], []),
  'deleteEvent' : IDL.Func([IDL.Nat64], [], []),
  'deleteGalleryImage' : IDL.Func([IDL.Nat64], [], []),
  'getActivities' : IDL.Func([], [IDL.Vec(Activity)], ['query']),
  'getAlumniProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(AlumniProfile)],
      ['query'],
    ),
  'getAnnouncements' : IDL.Func([], [IDL.Vec(Announcement)], ['query']),
  'getAnnouncementsByYearRange' : IDL.Func(
      [IDL.Opt(IDL.Int16), IDL.Opt(IDL.Int16)],
      [IDL.Vec(Announcement)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(AlumniProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDepartments' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getEvents' : IDL.Func([IDL.Opt(IDL.Bool)], [IDL.Vec(Event)], ['query']),
  'getGalleryImages' : IDL.Func([], [IDL.Vec(GalleryImage)], ['query']),
  'getGraduationYears' : IDL.Func([], [IDL.Vec(IDL.Nat16)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(AlumniProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
  'listApprovalStates' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, ApprovalStatus))],
      ['query'],
    ),
  'listApprovalStatesWithProfiles' : IDL.Func(
      [],
      [
        IDL.Vec(
          IDL.Tuple(IDL.Principal, ApprovalStatus, IDL.Opt(AlumniProfile))
        ),
      ],
      ['query'],
    ),
  'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
  'requestApproval' : IDL.Func([], [], []),
  'saveAlumniProfile' : IDL.Func([AlumniProfile], [], []),
  'saveCallerUserProfile' : IDL.Func([AlumniProfile], [], []),
  'searchAlumniProfiles' : IDL.Func(
      [IDL.Opt(IDL.Nat16), IDL.Opt(IDL.Text)],
      [IDL.Vec(AlumniProfile)],
      ['query'],
    ),
  'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
  'updateActivity' : IDL.Func([IDL.Nat64, EditableActivity], [], []),
  'updateEvent' : IDL.Func([IDL.Nat64, EditableEvent], [], []),
  'updateGalleryImage' : IDL.Func([IDL.Nat64, EditableGalleryImage], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const EditableActivity = IDL.Record({
    'title' : IDL.Text,
    'description' : IDL.Text,
    'photos' : IDL.Vec(IDL.Text),
  });
  const EditableAnnouncement = IDL.Record({
    'title' : IDL.Text,
    'content' : IDL.Text,
  });
  const EditableEvent = IDL.Record({
    'title' : IDL.Text,
    'description' : IDL.Text,
    'location' : IDL.Text,
    'timestampNanos' : IDL.Nat64,
  });
  const EditableGalleryImage = IDL.Record({
    'title' : IDL.Text,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
  });
  const Activity = IDL.Record({
    'id' : IDL.Nat64,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'timestampNanos' : IDL.Int,
    'photos' : IDL.Vec(IDL.Text),
  });
  const AlumniProfile = IDL.Record({
    'bio' : IDL.Text,
    'contactInfo' : IDL.Opt(IDL.Text),
    'currentCountry' : IDL.Text,
    'fullName' : IDL.Text,
    'graduationYear' : IDL.Nat16,
    'currentCity' : IDL.Text,
    'department' : IDL.Text,
  });
  const Announcement = IDL.Record({
    'id' : IDL.Nat64,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'timestampNanos' : IDL.Int,
  });
  const Event = IDL.Record({
    'id' : IDL.Nat64,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'location' : IDL.Text,
    'timestampNanos' : IDL.Nat64,
  });
  const GalleryImage = IDL.Record({
    'id' : IDL.Nat64,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'timestampNanos' : IDL.Int,
  });
  const ApprovalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const UserApprovalInfo = IDL.Record({
    'status' : ApprovalStatus,
    'principal' : IDL.Principal,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createActivity' : IDL.Func([EditableActivity], [], []),
    'createAnnouncement' : IDL.Func([EditableAnnouncement], [], []),
    'createEvent' : IDL.Func([EditableEvent], [], []),
    'createGalleryImage' : IDL.Func([EditableGalleryImage], [], []),
    'deleteActivity' : IDL.Func([IDL.Nat64], [], []),
    'deleteAnnouncement' : IDL.Func([IDL.Nat64], [], []),
    'deleteEvent' : IDL.Func([IDL.Nat64], [], []),
    'deleteGalleryImage' : IDL.Func([IDL.Nat64], [], []),
    'getActivities' : IDL.Func([], [IDL.Vec(Activity)], ['query']),
    'getAlumniProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(AlumniProfile)],
        ['query'],
      ),
    'getAnnouncements' : IDL.Func([], [IDL.Vec(Announcement)], ['query']),
    'getAnnouncementsByYearRange' : IDL.Func(
        [IDL.Opt(IDL.Int16), IDL.Opt(IDL.Int16)],
        [IDL.Vec(Announcement)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(AlumniProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDepartments' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getEvents' : IDL.Func([IDL.Opt(IDL.Bool)], [IDL.Vec(Event)], ['query']),
    'getGalleryImages' : IDL.Func([], [IDL.Vec(GalleryImage)], ['query']),
    'getGraduationYears' : IDL.Func([], [IDL.Vec(IDL.Nat16)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(AlumniProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
    'listApprovalStates' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, ApprovalStatus))],
        ['query'],
      ),
    'listApprovalStatesWithProfiles' : IDL.Func(
        [],
        [
          IDL.Vec(
            IDL.Tuple(IDL.Principal, ApprovalStatus, IDL.Opt(AlumniProfile))
          ),
        ],
        ['query'],
      ),
    'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
    'requestApproval' : IDL.Func([], [], []),
    'saveAlumniProfile' : IDL.Func([AlumniProfile], [], []),
    'saveCallerUserProfile' : IDL.Func([AlumniProfile], [], []),
    'searchAlumniProfiles' : IDL.Func(
        [IDL.Opt(IDL.Nat16), IDL.Opt(IDL.Text)],
        [IDL.Vec(AlumniProfile)],
        ['query'],
      ),
    'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
    'updateActivity' : IDL.Func([IDL.Nat64, EditableActivity], [], []),
    'updateEvent' : IDL.Func([IDL.Nat64, EditableEvent], [], []),
    'updateGalleryImage' : IDL.Func([IDL.Nat64, EditableGalleryImage], [], []),
  });
};

export const init = ({ IDL }) => { return []; };