/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const EditableAnnouncement = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
});
export const EditableEvent = IDL.Record({
  'title' : IDL.Text,
  'description' : IDL.Text,
  'location' : IDL.Text,
  'timestampNanos' : IDL.Nat64,
});
export const AlumniProfile = IDL.Record({
  'bio' : IDL.Text,
  'contactInfo' : IDL.Opt(IDL.Text),
  'currentCountry' : IDL.Text,
  'fullName' : IDL.Text,
  'graduationYear' : IDL.Nat16,
  'currentCity' : IDL.Text,
  'department' : IDL.Text,
});
export const Announcement = IDL.Record({
  'id' : IDL.Nat64,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'timestampNanos' : IDL.Int,
});
export const Event = IDL.Record({
  'id' : IDL.Nat64,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'location' : IDL.Text,
  'timestampNanos' : IDL.Nat64,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createAnnouncement' : IDL.Func([EditableAnnouncement], [], []),
  'createEvent' : IDL.Func([EditableEvent], [], []),
  'deleteAnnouncement' : IDL.Func([IDL.Nat64], [], []),
  'deleteEvent' : IDL.Func([IDL.Nat64], [], []),
  'getAlumniProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(AlumniProfile)],
      ['query'],
    ),
  'getAnnouncements' : IDL.Func([], [IDL.Vec(Announcement)], ['query']),
  'getAnnouncementsByYearRange' : IDL.Func(
      [IDL.Opt(IDL.Int16), IDL.Opt(IDL.Int16)],
      [IDL.Vec(Announcement)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(AlumniProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDepartments' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getEvents' : IDL.Func([IDL.Opt(IDL.Bool)], [IDL.Vec(Event)], ['query']),
  'getGraduationYears' : IDL.Func([], [IDL.Vec(IDL.Nat16)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(AlumniProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveAlumniProfile' : IDL.Func([AlumniProfile], [], []),
  'saveCallerUserProfile' : IDL.Func([AlumniProfile], [], []),
  'searchAlumniProfiles' : IDL.Func(
      [IDL.Opt(IDL.Nat16), IDL.Opt(IDL.Text)],
      [IDL.Vec(AlumniProfile)],
      ['query'],
    ),
  'updateEvent' : IDL.Func([IDL.Nat64, EditableEvent], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const EditableAnnouncement = IDL.Record({
    'title' : IDL.Text,
    'content' : IDL.Text,
  });
  const EditableEvent = IDL.Record({
    'title' : IDL.Text,
    'description' : IDL.Text,
    'location' : IDL.Text,
    'timestampNanos' : IDL.Nat64,
  });
  const AlumniProfile = IDL.Record({
    'bio' : IDL.Text,
    'contactInfo' : IDL.Opt(IDL.Text),
    'currentCountry' : IDL.Text,
    'fullName' : IDL.Text,
    'graduationYear' : IDL.Nat16,
    'currentCity' : IDL.Text,
    'department' : IDL.Text,
  });
  const Announcement = IDL.Record({
    'id' : IDL.Nat64,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'timestampNanos' : IDL.Int,
  });
  const Event = IDL.Record({
    'id' : IDL.Nat64,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'location' : IDL.Text,
    'timestampNanos' : IDL.Nat64,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createAnnouncement' : IDL.Func([EditableAnnouncement], [], []),
    'createEvent' : IDL.Func([EditableEvent], [], []),
    'deleteAnnouncement' : IDL.Func([IDL.Nat64], [], []),
    'deleteEvent' : IDL.Func([IDL.Nat64], [], []),
    'getAlumniProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(AlumniProfile)],
        ['query'],
      ),
    'getAnnouncements' : IDL.Func([], [IDL.Vec(Announcement)], ['query']),
    'getAnnouncementsByYearRange' : IDL.Func(
        [IDL.Opt(IDL.Int16), IDL.Opt(IDL.Int16)],
        [IDL.Vec(Announcement)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(AlumniProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDepartments' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getEvents' : IDL.Func([IDL.Opt(IDL.Bool)], [IDL.Vec(Event)], ['query']),
    'getGraduationYears' : IDL.Func([], [IDL.Vec(IDL.Nat16)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(AlumniProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveAlumniProfile' : IDL.Func([AlumniProfile], [], []),
    'saveCallerUserProfile' : IDL.Func([AlumniProfile], [], []),
    'searchAlumniProfiles' : IDL.Func(
        [IDL.Opt(IDL.Nat16), IDL.Opt(IDL.Text)],
        [IDL.Vec(AlumniProfile)],
        ['query'],
      ),
    'updateEvent' : IDL.Func([IDL.Nat64, EditableEvent], [], []),
  });
};

export const init = ({ IDL }) => { return []; };